[package]
name = "cw-core-interface"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema = "1.1.0"
cosmwasm-std = "1.1.0"
cw-core-macros = { version = "1.1.0", path = "../../packages/cw-core-macros" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
schemars = "0.8"
cw2 = "0.15.0"

[dev-dependencies]
