[package]
name = "cw-paginate"
version = "1.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = "1.1"
cosmwasm-storage = "1.1"
cw-storage-plus = "0.16"
serde = { version = "1.0", default-features = false }

[dev-dependencies]
cw-multi-test = "0.16"
